job('Seed_Job_child') {
    description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
    scm {
        git("https://github.com/vra0613/maven-project.git", 'main')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        mvn('clean package', 'maven-samples/pom.xml')
    }
    
}
